### ISSUE TITLE
Hide access info for Travis

### ISSUE THREAD

**Issue by rtsio** [psychomieze/sauceExtension#5]
Trying to use this package with Travis CI, but hitting a problem; I can't use a private local .yml file for the credentials, as they need to be in the repo for Travis to use them and start up the extension. Travis/Sauce solve this by closely integrating and encrypting the Sauce credentials for Travis to use, but this is all for naught if I want to use Codeception and this Extension, because I will have to push a file with credentials to the repo anyway. Thoughts?

**Comment by susannemoog** [comment]
Merged the pull request, sorry it took so long.
