### ISSUE TITLE
Please change to a more permissive license

### ISSUE THREAD

**Issue by motin** [psychomieze/sauceExtension#8]
Hi, any change that you can release this under BSD-3 or MIT? Or at least Apache 2 like Sausage?

**Comment by PommeVerte** [comment]
I'd like to second this. I'm playing around with it right now but my efforts will go to waste if the license stays as is.

**Comment by psychomieze** [comment]
Done. Hope that helps (have no time anymore for this project).

**Comment by motin** [comment]
As a result of the less permissive license previously, this project sprung up: https://github.com/neam/codeception-saucelabs-metadata

**Comment by dmill-bz** [comment]
great news. Thanks
